### ISSUE TITLE
label not showing full text

### ISSUE THREAD

**Issue by RedHatter** [halfnelson/svelte-native#110]
When using the slot of a label only the last "segment" is rendered. The following only renders "two"
```
<script>
  const one = 'one'
  const two = 'two'
</script>

<page>
  <label>{one} {two}</label>
</page>
```
When the text property is used instead it works as intended.
```
<script>
  const one = 'one'
  const two = 'two'
</script>

<page>
  <label text="{one} {two}"></label>
</page>
```

**Comment by halfnelson** [comment]
Thanks for the report. This seems to be because svelte compiles that down to 3 text nodes, and the text node handler in the DOM implementation just sets the text attribute of the parent each time a child text note is updated with the text of that child. I will update it so that updating a text element, sets the value to that of the combined text child nodes

**Comment by RedHatter** [comment]
Any update on this? This issue is a bit of a blocker for us.
