### ISSUE TITLE
production ready?

### ISSUE THREAD

**Issue by sido420** [halfnelson/svelte-native#161]
Thanks for the Svelte Native framework. I liked what I have seen so far. 

However, before I invest more time and energy, I wanted to know if Svelte Native is production ready yet or not?

Are there any pending issues that may cause major issues for app developers? Are most/all Nativescript features available through Svelte Native? Is the Svelte Native framework ready for complex apps? 

Please feel free to add other details along the lines of above. This would help other developers make informed decisions for  their new/future projects.

**Comment by Natetronn** [comment]
Following...

**Comment by halfnelson** [comment]
It is the least supported of the Nativescript frameworks. People have put it in production since the joy of Svelte is sometimes worth the risk :). From my limited knowledge, most serious apps are either Nativescript Core, Angular or Vue (as these were all official packages and the maintainers are on the core nativescript team). I try to fix bugs when I come across them or when they are reported. I also advocate for svelte-native concerns with svelte maintainers.

**Comment by sido420** [comment]
Thanks. Please update this issue if things change in future.
