### ISSUE TITLE
How to make this compatible with Svelte Material UI

### ISSUE THREAD

**Issue by Egnus** [halfnelson/svelte-native#57]
Hi,
I have been dealing some days with this already but i did not manage to use the components from https://github.com/hperrin/svelte-material-ui

despite the fact that is a pretty straight forward project, i couldn't solve an issue with the svelte-loader.
Particularly this one:
`Error: Function called outside component initialization`

Mainly coming from Svelte function get_current_component()
`Frame: function:'get_current_component', file:'file:///node_modules/svelte/internal/index.js:532:0`

Is there any way I can solve this issue or that svelte native supports this library?

**Comment by hperrin** [comment]
SMUI is based on the Material Web Components, which heavily depend on the DOM. I'd like to eventually provide a compatible version for Svelte Native, but that probably won't be for a while.

**Comment by halfnelson** [comment]
Yes, svelte component libraries are not likely to work out of the box with svelte-native since most will be based on browser DOM (div, h1, etc) where svelte-native needs native components like listView and actionBar. You can style your nativescript application to be more material like : https://www.nativescript.org/blog/an-early-look-at-the-new-nativescript-core-theme

**Comment by hperrin** [comment]
I'd like to create a preprocessor to basically do things like

```
<markup env=web>
  ...
</markup>
<script env=native>
  ...
</script>
```

**Comment by hperrin** [comment]
Then it may be possible.
