### ISSUE TITLE
SvelteNativeDom: Navigate could not find frame with id

### ISSUE THREAD

**Issue by crisgol** [halfnelson/svelte-native#82]
error on 

 navigate({
            page: Tabs,
            frame:"firstFrame"
        })

not find   frame .

**Comment by halfnelson** [comment]
@crisgol Thanks for the report. Upon investigation it seems that this happens when calling navigate before the frame component has been attached to nativescript's view hierarchy. Svelte likes to mount the child components first.
The problem mainly happens when you are trying to navigate the frame to the first page of your application, you can work around this in the following ways:

**Wait for the component containing the frame to be added to the main view.**

Svelte has the `tick` method to help with this,
```js
  onMount(async () => {
        await tick();
        navigate({ page: MainPage, frame: "my-frame-id" });
    })
```
**Set the default page using the defautPage attribute of the frame**

```html
<frame defaultPage="{MainPage}">
```

**Set the default page as child of frame**

```html
  <frame>
      <MainPage />
   </frame>
```

**Comment by halfnelson** [comment]
I must have had a false positive test, the tick method does not work. Re-opening

**Comment by jquesada2016** [comment]
Any progress on this? I had something similar to this issue, but it was that I was navigating to a page (on same frame) as soon as the app opened, and it would crash because the component didn't exist. I did not use, however, the tick() function. I used a timeout with a value of 0 and that worked for me. However, with a frame, it does not work, even if I wait a few seconds...
